version: '3.9'

#networks:
#  dev_network:

services:
  db:
    image: postgres:14.3-alpine3.15
    hostname: '127.0.0.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: .
    environment:
      PG_DSN: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}'
    ports:
      - '8000:8080'
    depends_on:
      - db
    volumes:
      - ./app:/app